"""Configuration module for core constants and settings."""

from .constants import (
    # Modbus address prefixes
    MODBUS_COIL_PREFIX,
    MODBUS_DISCRETE_PREFIX,
    MODBUS_INPUT_REG_PREFIX,
    MODBUS_HOLDING_REG_PREFIX,
    # Modbus address constants
    MODBUS_ADDRESS_OFFSET,
    MODBUS_SEQUENCE_WIDTH,
    MODBUS_ADDRESS_RANGES,
    # Modbus defaults
    MODBUS_DEFAULT_SCAN_RATE,
    MODBUS_DEFAULT_BAUD_RATE,
    MODBUS_DEFAULT_TIMEOUT,
    MODBUS_DEFAULT_TIMING,
    MODBUS_DEFAULT_DATA_ACCESS,
    MODBUS_DEFAULT_BLOCK_SIZES,
    MODBUS_DEFAULT_ENCODING,
    MODBUS_DEFAULT_SERIAL_COMM,
    MODBUS_DEFAULT_TCP_COMM,
    MODBUS_DEFAULT_TAG,
    MODBUS_DEFAULT_TAG_SCALING,
    MODBUS_DEFAULT_MAX_REGS,
    MODBUS_DEFAULT_OUT_COILS,
    MODBUS_DEFAULT_IN_COILS,
    # Buffer constants
    DATA_BUFFER_MAX_SIZE,
    DATA_BUFFER_MAX_AGE,
    # Hierarchy constants
    GROUP_SEPARATOR,
    # OPC UA constants
    OPC_UA_DEFAULT_ENDPOINT,
    OPC_UA_DEFAULT_NAMESPACE,
    OPC_UA_DEFAULT_PORT,
    # CSV constants
    CSV_FIELD_NAMES,
)

__all__ = [
    "MODBUS_COIL_PREFIX",
    "MODBUS_DISCRETE_PREFIX",
    "MODBUS_INPUT_REG_PREFIX",
    "MODBUS_HOLDING_REG_PREFIX",
    "MODBUS_ADDRESS_OFFSET",
    "MODBUS_SEQUENCE_WIDTH",
    "MODBUS_ADDRESS_RANGES",
    "MODBUS_DEFAULT_SCAN_RATE",
    "MODBUS_DEFAULT_BAUD_RATE",
    "MODBUS_DEFAULT_TIMEOUT",
    "MODBUS_DEFAULT_TIMING",
    "MODBUS_DEFAULT_DATA_ACCESS",
    "MODBUS_DEFAULT_BLOCK_SIZES",
    "MODBUS_DEFAULT_ENCODING",
    "MODBUS_DEFAULT_SERIAL_COMM",
    "MODBUS_DEFAULT_TCP_COMM",
    "MODBUS_DEFAULT_TAG",
    "MODBUS_DEFAULT_TAG_SCALING",
    "MODBUS_DEFAULT_MAX_REGS",
    "MODBUS_DEFAULT_OUT_COILS",
    "MODBUS_DEFAULT_IN_COILS",
    "DATA_BUFFER_MAX_SIZE",
    "DATA_BUFFER_MAX_AGE",
    "GROUP_SEPARATOR",
    "OPC_UA_DEFAULT_ENDPOINT",
    "OPC_UA_DEFAULT_NAMESPACE",
    "OPC_UA_DEFAULT_PORT",
    "CSV_FIELD_NAMES",
]
